# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.11.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.11.3/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/Peter/work/code/Zilliqa

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/Peter/work/code/Zilliqa

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.11.3/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.11.3/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Peter/work/code/Zilliqa/CMakeFiles /Users/Peter/work/code/Zilliqa/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/Peter/work/code/Zilliqa/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Constants

# Build rule for target.
Constants: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Constants
.PHONY : Constants

# fast build rule for target.
Constants/fast:
	$(MAKE) -f src/common/CMakeFiles/Constants.dir/build.make src/common/CMakeFiles/Constants.dir/build
.PHONY : Constants/fast

#=============================================================================
# Target rules for targets named Common

# Build rule for target.
Common: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Common
.PHONY : Common

# fast build rule for target.
Common/fast:
	$(MAKE) -f src/depends/common/CMakeFiles/Common.dir/build.make src/depends/common/CMakeFiles/Common.dir/build
.PHONY : Common/fast

#=============================================================================
# Target rules for targets named Database

# Build rule for target.
Database: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Database
.PHONY : Database

# fast build rule for target.
Database/fast:
	$(MAKE) -f src/depends/libDatabase/CMakeFiles/Database.dir/build.make src/depends/libDatabase/CMakeFiles/Database.dir/build
.PHONY : Database/fast

#=============================================================================
# Target rules for targets named ethash

# Build rule for target.
ethash: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ethash
.PHONY : ethash

# fast build rule for target.
ethash/fast:
	$(MAKE) -f src/depends/libethash/CMakeFiles/ethash.dir/build.make src/depends/libethash/CMakeFiles/ethash.dir/build
.PHONY : ethash/fast

#=============================================================================
# Target rules for targets named Trie

# Build rule for target.
Trie: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Trie
.PHONY : Trie

# fast build rule for target.
Trie/fast:
	$(MAKE) -f src/depends/libTrie/CMakeFiles/Trie.dir/build.make src/depends/libTrie/CMakeFiles/Trie.dir/build
.PHONY : Trie/fast

#=============================================================================
# Target rules for targets named minilzo

# Build rule for target.
minilzo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 minilzo
.PHONY : minilzo

# fast build rule for target.
minilzo/fast:
	$(MAKE) -f src/depends/minilzo/CMakeFiles/minilzo.dir/build.make src/depends/minilzo/CMakeFiles/minilzo.dir/build
.PHONY : minilzo/fast

#=============================================================================
# Target rules for targets named Sha3

# Build rule for target.
Sha3: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Sha3
.PHONY : Sha3

# fast build rule for target.
Sha3/fast:
	$(MAKE) -f src/depends/Sha3/CMakeFiles/Sha3.dir/build.make src/depends/Sha3/CMakeFiles/Sha3.dir/build
.PHONY : Sha3/fast

#=============================================================================
# Target rules for targets named NAT

# Build rule for target.
NAT: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NAT
.PHONY : NAT

# fast build rule for target.
NAT/fast:
	$(MAKE) -f src/depends/NAT/CMakeFiles/NAT.dir/build.make src/depends/NAT/CMakeFiles/NAT.dir/build
.PHONY : NAT/fast

#=============================================================================
# Target rules for targets named Consensus

# Build rule for target.
Consensus: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Consensus
.PHONY : Consensus

# fast build rule for target.
Consensus/fast:
	$(MAKE) -f src/libConsensus/CMakeFiles/Consensus.dir/build.make src/libConsensus/CMakeFiles/Consensus.dir/build
.PHONY : Consensus/fast

#=============================================================================
# Target rules for targets named Crypto

# Build rule for target.
Crypto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Crypto
.PHONY : Crypto

# fast build rule for target.
Crypto/fast:
	$(MAKE) -f src/libCrypto/CMakeFiles/Crypto.dir/build.make src/libCrypto/CMakeFiles/Crypto.dir/build
.PHONY : Crypto/fast

#=============================================================================
# Target rules for targets named AccountData

# Build rule for target.
AccountData: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 AccountData
.PHONY : AccountData

# fast build rule for target.
AccountData/fast:
	$(MAKE) -f src/libData/AccountData/CMakeFiles/AccountData.dir/build.make src/libData/AccountData/CMakeFiles/AccountData.dir/build
.PHONY : AccountData/fast

#=============================================================================
# Target rules for targets named Block

# Build rule for target.
Block: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Block
.PHONY : Block

# fast build rule for target.
Block/fast:
	$(MAKE) -f src/libData/BlockData/Block/CMakeFiles/Block.dir/build.make src/libData/BlockData/Block/CMakeFiles/Block.dir/build
.PHONY : Block/fast

#=============================================================================
# Target rules for targets named BlockHeader

# Build rule for target.
BlockHeader: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BlockHeader
.PHONY : BlockHeader

# fast build rule for target.
BlockHeader/fast:
	$(MAKE) -f src/libData/BlockData/BlockHeader/CMakeFiles/BlockHeader.dir/build.make src/libData/BlockData/BlockHeader/CMakeFiles/BlockHeader.dir/build
.PHONY : BlockHeader/fast

#=============================================================================
# Target rules for targets named BlockChainData

# Build rule for target.
BlockChainData: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 BlockChainData
.PHONY : BlockChainData

# fast build rule for target.
BlockChainData/fast:
	$(MAKE) -f src/libData/BlockChainData/CMakeFiles/BlockChainData.dir/build.make src/libData/BlockChainData/CMakeFiles/BlockChainData.dir/build
.PHONY : BlockChainData/fast

#=============================================================================
# Target rules for targets named DirectoryService

# Build rule for target.
DirectoryService: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 DirectoryService
.PHONY : DirectoryService

# fast build rule for target.
DirectoryService/fast:
	$(MAKE) -f src/libDirectoryService/CMakeFiles/DirectoryService.dir/build.make src/libDirectoryService/CMakeFiles/DirectoryService.dir/build
.PHONY : DirectoryService/fast

#=============================================================================
# Target rules for targets named Lookup

# Build rule for target.
Lookup: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Lookup
.PHONY : Lookup

# fast build rule for target.
Lookup/fast:
	$(MAKE) -f src/libLookup/CMakeFiles/Lookup.dir/build.make src/libLookup/CMakeFiles/Lookup.dir/build
.PHONY : Lookup/fast

#=============================================================================
# Target rules for targets named Mediator

# Build rule for target.
Mediator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Mediator
.PHONY : Mediator

# fast build rule for target.
Mediator/fast:
	$(MAKE) -f src/libMediator/CMakeFiles/Mediator.dir/build.make src/libMediator/CMakeFiles/Mediator.dir/build
.PHONY : Mediator/fast

#=============================================================================
# Target rules for targets named Persistence

# Build rule for target.
Persistence: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Persistence
.PHONY : Persistence

# fast build rule for target.
Persistence/fast:
	$(MAKE) -f src/libPersistence/CMakeFiles/Persistence.dir/build.make src/libPersistence/CMakeFiles/Persistence.dir/build
.PHONY : Persistence/fast

#=============================================================================
# Target rules for targets named POW

# Build rule for target.
POW: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 POW
.PHONY : POW

# fast build rule for target.
POW/fast:
	$(MAKE) -f src/libPOW/CMakeFiles/POW.dir/build.make src/libPOW/CMakeFiles/POW.dir/build
.PHONY : POW/fast

#=============================================================================
# Target rules for targets named Network

# Build rule for target.
Network: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Network
.PHONY : Network

# fast build rule for target.
Network/fast:
	$(MAKE) -f src/libNetwork/CMakeFiles/Network.dir/build.make src/libNetwork/CMakeFiles/Network.dir/build
.PHONY : Network/fast

#=============================================================================
# Target rules for targets named Node

# Build rule for target.
Node: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Node
.PHONY : Node

# fast build rule for target.
Node/fast:
	$(MAKE) -f src/libNode/CMakeFiles/Node.dir/build.make src/libNode/CMakeFiles/Node.dir/build
.PHONY : Node/fast

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) -f src/libServer/CMakeFiles/Server.dir/build.make src/libServer/CMakeFiles/Server.dir/build
.PHONY : Server/fast

#=============================================================================
# Target rules for targets named Utils

# Build rule for target.
Utils: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Utils
.PHONY : Utils

# fast build rule for target.
Utils/fast:
	$(MAKE) -f src/libUtils/CMakeFiles/Utils.dir/build.make src/libUtils/CMakeFiles/Utils.dir/build
.PHONY : Utils/fast

#=============================================================================
# Target rules for targets named Validator

# Build rule for target.
Validator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Validator
.PHONY : Validator

# fast build rule for target.
Validator/fast:
	$(MAKE) -f src/libValidator/CMakeFiles/Validator.dir/build.make src/libValidator/CMakeFiles/Validator.dir/build
.PHONY : Validator/fast

#=============================================================================
# Target rules for targets named Zilliqa

# Build rule for target.
Zilliqa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Zilliqa
.PHONY : Zilliqa

# fast build rule for target.
Zilliqa/fast:
	$(MAKE) -f src/libZilliqa/CMakeFiles/Zilliqa.dir/build.make src/libZilliqa/CMakeFiles/Zilliqa.dir/build
.PHONY : Zilliqa/fast

#=============================================================================
# Target rules for targets named sendcmd

# Build rule for target.
sendcmd: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sendcmd
.PHONY : sendcmd

# fast build rule for target.
sendcmd/fast:
	$(MAKE) -f src/cmd/CMakeFiles/sendcmd.dir/build.make src/cmd/CMakeFiles/sendcmd.dir/build
.PHONY : sendcmd/fast

#=============================================================================
# Target rules for targets named genkeypair

# Build rule for target.
genkeypair: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 genkeypair
.PHONY : genkeypair

# fast build rule for target.
genkeypair/fast:
	$(MAKE) -f src/cmd/CMakeFiles/genkeypair.dir/build.make src/cmd/CMakeFiles/genkeypair.dir/build
.PHONY : genkeypair/fast

#=============================================================================
# Target rules for targets named sendtxn

# Build rule for target.
sendtxn: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sendtxn
.PHONY : sendtxn

# fast build rule for target.
sendtxn/fast:
	$(MAKE) -f src/cmd/CMakeFiles/sendtxn.dir/build.make src/cmd/CMakeFiles/sendtxn.dir/build
.PHONY : sendtxn/fast

#=============================================================================
# Target rules for targets named zilliqa

# Build rule for target.
zilliqa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 zilliqa
.PHONY : zilliqa

# fast build rule for target.
zilliqa/fast:
	$(MAKE) -f src/cmd/CMakeFiles/zilliqa.dir/build.make src/cmd/CMakeFiles/zilliqa.dir/build
.PHONY : zilliqa/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Constants"
	@echo "... Common"
	@echo "... Database"
	@echo "... ethash"
	@echo "... Trie"
	@echo "... minilzo"
	@echo "... Sha3"
	@echo "... NAT"
	@echo "... Consensus"
	@echo "... Crypto"
	@echo "... AccountData"
	@echo "... Block"
	@echo "... BlockHeader"
	@echo "... BlockChainData"
	@echo "... DirectoryService"
	@echo "... Lookup"
	@echo "... Mediator"
	@echo "... Persistence"
	@echo "... POW"
	@echo "... Network"
	@echo "... Node"
	@echo "... Server"
	@echo "... Utils"
	@echo "... Validator"
	@echo "... Zilliqa"
	@echo "... sendcmd"
	@echo "... genkeypair"
	@echo "... sendtxn"
	@echo "... zilliqa"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

